%YAML:1.0

# last
armour:
  debug: 0
  red_spilt_threshold: 95
  red_gray_threshold: 100
  red_green_threshold: 127
  blue_spilt_threshold: 125
  blue_gray_threshold: 125
  blue_green_threshold: 128
  light_contour_min: 10

energy:
  debug: 0
  debug_no_img: 1
  red_spilt_threshold: 45
  red_gray_threshold: 75
  red_green_threshold: 141
  blue_spilt_threshold: 80
  blue_gray_threshold: 110
  blue_green_threshold: 80
  fan_size_threshold: 3000
  area_rate_min: 0.4
  area_rate_max: 0.6

base:
  simple_pitch_diff: -0.040
  simple_yaw_diff: 0.010
  sentry_pitch_diff: 0.003
  sentry_yaw_diff: 0.018
  buff_pitch_diff: -0.040
  buff_yaw_diff: 0.010

ekf:
  # predict
  Q00: 0.1  #0.1
  Q11: 10  #10
  Q22: 0.1  #0.1
  Q33: 10 # 1
  Q44: 0.01  #0,01
  # measure
  R00: 1
  R11: 1
  R22: 800

