%YAML:1.0

armour:
  debug: 0
  red_spilt_threshold: 85
  red_gray_threshold: 94
  red_green_threshold: 164
  blue_spilt_threshold: 95
  blue_gray_threshold: 140
  blue_green_threshold: 100
  light_contour_min: 15

energy:
  debug: 0
  debug_no_img: 1
  red_spilt_threshold: 45
  red_gray_threshold: 75
  red_green_threshold: 45 #80
  blue_spilt_threshold: 80
  blue_gray_threshold: 110
  blue_green_threshold: 80
  fan_size_threshold: 3000
  area_rate_min: 0.4
  area_rate_max: 0.6

base:
  simple_pitch_diff: 0.005
  simple_yaw_diff: -0.021
  sentry_pitch_diff: 0.003
  sentry_yaw_diff: -0.021
  buff_pitch_diff: -0.01
  buff_yaw_diff: 0.025

ekf:
  # predict
  Q00: 0.1
  Q11: 10
  Q22: 0.1
  Q33: 1
  Q44: 0.01
  # measure
  R00: 1
  R11: 1
  R22: 800

