%YAML:1.0
# QUAN XIANG
armour:
  debug: 0
  red_spilt_threshold: 85
  red_gray_threshold: 115
  red_green_threshold: 95
  blue_spilt_threshold: 95
  blue_gray_threshold: 140
  blue_green_threshold: 108
  light_contour_min: 15

energy:
  debug: 0
  debug_no_img: 1
  red_spilt_threshold: 45
  red_gray_threshold: 75
  red_green_threshold: 141
  blue_spilt_threshold: 80
  blue_gray_threshold: 110
  blue_green_threshold: 80
  fan_size_threshold: 3000
  area_rate_min: 0.4
  area_rate_max: 0.6

base:
  simple_pitch_diff: 0.020
  simple_yaw_diff: 0.00
  sentry_pitch_diff: -0.005
  sentry_yaw_diff: -0.018
  buff_pitch_diff: 0.01
  buff_yaw_diff: 0.001


