%YAML:1.0

# old
armour:
  debug: 0
  red_spilt_threshold: 95
  red_gray_threshold: 90
  red_green_threshold: 160
  blue_spilt_threshold: 80
  blue_gray_threshold: 125
  blue_green_threshold: 60
  light_contour_min: 5

energy:
  debug: 0
  debug_no_img: 1
  red_spilt_threshold: 80
  red_gray_threshold: 58 #9  #58
  red_green_threshold: 82 #80
  blue_spilt_threshold: 80
  blue_gray_threshold: 110
  blue_green_threshold: 80
  fan_size_threshold: 300 #3000
  area_rate_min: 0.4
  area_rate_max: 0.6

base:
  simple_pitch_diff: 0.0
  simple_yaw_diff: -0.015
  sentry_pitch_diff: 0.007
  sentry_yaw_diff: -0.001
  buff_pitch_diff: 0.012
  buff_yaw_diff: -0.018
ekf:
  # predict
  Q00: 0.1
  Q11: 10
  Q22: 0.1
  Q33: 10
  Q44: 0.01
  # measure
  R00: 1
  R11: 1
  R22: 800

anti_ekf:
  # predict
  Q00: 0.01
  Q11: 100
  Q22: 0.01
  Q33: 100
  Q44: 0.01
  # measure
  R00: 1
  R11: 1
  R22: 800
